/*
 * AboutDialog.java
 *
 * Copyright (C) 2009 Beselius
 *
 * This file is part of Birch.
 *
 * Birch is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Birch is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Birch.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AboutDialog.java
 *
 * Created on 27.05.2009, 23:35:26
 */
package birch.gui;

import java.io.*;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Beselius
 */
public class AboutDialog extends javax.swing.JDialog {

   /** Creates new form AboutDialog */
   public AboutDialog(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
      initComponents();

      // Insert license text to text area and scroll up again.
      licenseTextArea.setText(getLicenseText());
      licenseTextArea.setCaretPosition(0);
   }

   private String getLicenseText() {
      InputStream ressource;
      StringBuilder result;
      BufferedReader reader;
      String line;

      result = new StringBuilder();

      ressource = getClass().getResourceAsStream("/GPL-3");
      if (ressource != null) {
         reader = new BufferedReader(new InputStreamReader(ressource));
         try {
            while ((line = reader.readLine()) != null) {
               result.append(line);
               result.append('\n');
            }
         } catch (IOException ex) {
            Logger.getLogger(AboutDialog.class.getName()).log(Level.SEVERE, null, ex);
         } finally {
            try {
               reader.close();
            } catch (IOException ex) {
               Logger.getLogger(AboutDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
      }

      return result.toString();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      closeButton = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      licenseTextArea = new javax.swing.JTextArea();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("birch/gui/Bundle"); // NOI18N
      setTitle(bundle.getString("About")); // NOI18N
      setLocationByPlatform(true);
      setMinimumSize(new java.awt.Dimension(250, 250));
      setModal(true);

      closeButton.setText(bundle.getString("close")); // NOI18N
      closeButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeButtonActionPerformed(evt);
         }
      });

      licenseTextArea.setColumns(79);
      licenseTextArea.setEditable(false);
      licenseTextArea.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12));
      licenseTextArea.setRows(5);
      jScrollPane1.setViewportView(licenseTextArea);

      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birch/icon/Birch logo.png"))); // NOI18N
      jLabel1.setText("Copyright (C) 2009");
      jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

      jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel2.setText("Beselius <bsel@kommandostab.de>");

      jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel3.setText("s4msung <s4msung@exigen.org>");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
               .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
               .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(closeButton)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
       setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton closeButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea licenseTextArea;
   // End of variables declaration//GEN-END:variables
}
