/*
 * MainFrame.java
 *
 * Copyright (C) 2009 Beselius
 *
 * This file is part of Birch.
 *
 * Birch is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Birch is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Birch.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * MainFrame.java
 *
 * Created on 21.05.2009, 20:00:00
 */

package birch.gui;

import javax.swing.JMenuItem;
import javax.swing.JTabbedPane;

/**
 *
 * @author Beselius
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      tabbedPane = new javax.swing.JTabbedPane();
      jPanel1 = new javax.swing.JPanel();
      filterConfigurationPanel = new birch.gui.FilterConfigurationPanel();
      serverConfigurationPanel = new birch.gui.ServerConfigurationPanel();
      serverListPanel = new birch.gui.ServerListPanel();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      exitMenuItem = new javax.swing.JMenuItem();
      jMenu2 = new javax.swing.JMenu();
      aboutMenuItem = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Birch - Simple IRC Proxy with Filters");

      jPanel1.setLayout(new java.awt.BorderLayout());
      jPanel1.add(filterConfigurationPanel, java.awt.BorderLayout.CENTER);
      jPanel1.add(serverConfigurationPanel, java.awt.BorderLayout.NORTH);

      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("birch/gui/Bundle"); // NOI18N
      tabbedPane.addTab(bundle.getString("Server_Start"), jPanel1); // NOI18N
      tabbedPane.addTab(bundle.getString("Server_List"), serverListPanel); // NOI18N

      jMenu1.setText("Birch");

      exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
      exitMenuItem.setText(bundle.getString("exit")); // NOI18N
      jMenu1.add(exitMenuItem);

      jMenuBar1.add(jMenu1);

      jMenu2.setText(bundle.getString("Help")); // NOI18N

      aboutMenuItem.setText(bundle.getString("About")); // NOI18N
      jMenu2.add(aboutMenuItem);

      jMenuBar1.add(jMenu2);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenuItem aboutMenuItem;
   private javax.swing.JMenuItem exitMenuItem;
   private birch.gui.FilterConfigurationPanel filterConfigurationPanel;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JPanel jPanel1;
   private birch.gui.ServerConfigurationPanel serverConfigurationPanel;
   private birch.gui.ServerListPanel serverListPanel;
   private javax.swing.JTabbedPane tabbedPane;
   // End of variables declaration//GEN-END:variables

   public JMenuItem getExitMenuItem() {
      return exitMenuItem;
   }

   public JMenuItem getAboutMenuItem() {
      return aboutMenuItem;
   }

   public ServerConfigurationPanel getServerConfigurationPanel() {
      return serverConfigurationPanel;
   }

   public FilterConfigurationPanel getFilterConfigurationPanel() {
      return filterConfigurationPanel;
   }

   public ServerListPanel getServerListPanel() {
      return serverListPanel;
   }

   public JTabbedPane getTabbedPane() {
      return tabbedPane;
   }

}
