/*
 * ServerConfigurationPanel.java
 *
 * Copyright (C) 2009 Beselius
 *
 * This file is part of Birch.
 *
 * Birch is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Birch is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Birch.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * ServerConfiguration.java
 *
 * Created on 21.05.2009, 22:54:43
 */
package birch.gui;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Beselius
 */
public class ServerConfigurationPanel extends javax.swing.JPanel {

   /** Creates new form ServerConfiguration */
   public ServerConfigurationPanel() {
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      hostLabel = new javax.swing.JLabel();
      hostTextField = new javax.swing.JTextField();
      portLabel = new javax.swing.JLabel();
      portTextField = new javax.swing.JTextField();
      startServerButton = new javax.swing.JButton();
      proxyPortLabel = new javax.swing.JLabel();
      proxyPortTextField = new javax.swing.JTextField();
      proxyAddressLabel = new javax.swing.JLabel();
      proxyAddressTextField = new javax.swing.JTextField();

      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("birch/gui/Bundle"); // NOI18N
      hostLabel.setText(bundle.getString("server_host")); // NOI18N

      portLabel.setText(bundle.getString("server_port")); // NOI18N

      startServerButton.setText(bundle.getString("start_server")); // NOI18N

      proxyPortLabel.setText(bundle.getString("proxy_port")); // NOI18N

      proxyAddressLabel.setText(bundle.getString("proxy_address")); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(hostLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                     .addComponent(portLabel)
                     .addComponent(proxyPortLabel)
                     .addComponent(proxyAddressLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(hostTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                     .addComponent(portTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                     .addComponent(proxyPortTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                     .addComponent(proxyAddressTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
               .addComponent(startServerButton, javax.swing.GroupLayout.Alignment.TRAILING))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(hostLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(portLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(proxyPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(proxyPortLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(proxyAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(proxyAddressLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(startServerButton)
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel hostLabel;
   private javax.swing.JTextField hostTextField;
   private javax.swing.JLabel portLabel;
   private javax.swing.JTextField portTextField;
   private javax.swing.JLabel proxyAddressLabel;
   private javax.swing.JTextField proxyAddressTextField;
   private javax.swing.JLabel proxyPortLabel;
   private javax.swing.JTextField proxyPortTextField;
   private javax.swing.JButton startServerButton;
   // End of variables declaration//GEN-END:variables

   public JButton getStartServerButton() {
      return startServerButton;
   }

   public JTextField getHostTextField() {
      return hostTextField;
   }

   public JTextField getPortTextField() {
      return portTextField;
   }

   public JTextField getProxyPortTextField() {
      return proxyPortTextField;
   }

   public JTextField getProxyAddressTextField() {
      return proxyAddressTextField;
   }
}
